// <auto-generated />
using System;
using System.Collections.Generic;
using Emergency_Response_Simulator.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Emergency_Response_Simulator.Data.Migrations
{
    [DbContext(typeof(ErsDbContext))]
    partial class ErsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Jurisdiction")
                        .HasColumnType("text")
                        .HasColumnName("jurisdiction");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("short_name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_agencies");

                    b.ToTable("agencies", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedById")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("AcknowledgedById")
                        .HasDatabaseName("ix_alerts_acknowledged_by_id");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_alerts_incident_id");

                    b.HasIndex("RaisedAt")
                        .HasDatabaseName("ix_alerts_raised_at");

                    b.HasIndex("UnitId")
                        .HasDatabaseName("ix_alerts_unit_id");

                    b.ToTable("alerts", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.GisFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Geometry>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("geometry");

                    b.Property<Guid>("LayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("layer_id");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.HasKey("Id")
                        .HasName("pk_gis_features");

                    b.HasIndex("Geometry")
                        .HasDatabaseName("ix_gis_features_geometry");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geometry"), "gist");

                    b.HasIndex("LayerId")
                        .HasDatabaseName("ix_gis_features_layer_id");

                    b.ToTable("gis_features", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.GisLayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("key");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("VisibleByDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("visible_by_default");

                    b.HasKey("Id")
                        .HasName("pk_gis_layers");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_gis_layers_key");

                    b.ToTable("gis_layers", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Incident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("address");

                    b.Property<int>("CasualtiesConfirmed")
                        .HasColumnType("integer")
                        .HasColumnName("casualties_confirmed");

                    b.Property<int>("CasualtiesReported")
                        .HasColumnType("integer")
                        .HasColumnName("casualties_reported");

                    b.Property<bool>("EvacuationRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("evacuation_required");

                    b.Property<Guid?>("IncidentCommanderId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_commander_id");

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("number");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.PrimitiveCollection<List<string>>("Threats")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("threats");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_incidents");

                    b.HasIndex("IncidentCommanderId")
                        .HasDatabaseName("ix_incidents_incident_commander_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_incidents_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ix_incidents_number");

                    b.ToTable("incidents", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.IncidentActionPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by_id");

                    b.Property<string>("CommandersIntent")
                        .HasColumnType("text")
                        .HasColumnName("commanders_intent");

                    b.Property<string>("CommunicationsPlan")
                        .HasColumnType("text")
                        .HasColumnName("communications_plan");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("MedicalPlan")
                        .HasColumnType("text")
                        .HasColumnName("medical_plan");

                    b.Property<Guid>("OperationalPeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("operational_period_id");

                    b.Property<Guid?>("PreparedById")
                        .HasColumnType("uuid")
                        .HasColumnName("prepared_by_id");

                    b.Property<string>("SafetyMessage")
                        .HasColumnType("text")
                        .HasColumnName("safety_message");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_incident_action_plans");

                    b.HasIndex("ApprovedById")
                        .HasDatabaseName("ix_incident_action_plans_approved_by_id");

                    b.HasIndex("OperationalPeriodId")
                        .HasDatabaseName("ix_incident_action_plans_operational_period_id");

                    b.HasIndex("PreparedById")
                        .HasDatabaseName("ix_incident_action_plans_prepared_by_id");

                    b.HasIndex("IncidentId", "OperationalPeriodId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_incident_action_plans_incident_id_operational_period_id_ver");

                    b.ToTable("incident_action_plans", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.OperationalPeriod", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("End")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<DateTimeOffset>("Start")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start");

                    b.HasKey("Id")
                        .HasName("pk_operational_periods");

                    b.HasIndex("IncidentId", "Number")
                        .IsUnique()
                        .HasDatabaseName("ix_operational_periods_incident_id_number");

                    b.ToTable("operational_periods", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Claim")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("claim");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("confidence");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<double?>("LocationAccuracyMeters")
                        .HasColumnType("double precision")
                        .HasColumnName("location_accuracy_meters");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_name");

                    b.Property<string>("Verification")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("verification");

                    b.HasKey("Id")
                        .HasName("pk_reports");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_reports_incident_id");

                    b.HasIndex("ReceivedAt")
                        .HasDatabaseName("ix_reports_received_at");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Resource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("kind");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,4326)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("resource_type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("resource_type");

                    b.HasKey("Id")
                        .HasName("pk_resources");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_resources_agency_id");

                    b.HasIndex("Location")
                        .HasDatabaseName("ix_resources_location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.ToTable("resources", (string)null);

                    b.HasDiscriminator<string>("resource_type").HasValue("resource");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AgencyId")
                        .HasColumnType("uuid")
                        .HasColumnName("agency_id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("display_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("AgencyId")
                        .HasDatabaseName("ix_users_agency_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Zone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Geometry>("Area")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry,4326)")
                        .HasColumnName("area");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_from");

                    b.Property<DateTimeOffset?>("EffectiveUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("effective_until");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_zones");

                    b.HasIndex("Area")
                        .HasDatabaseName("ix_zones_area");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Area"), "gist");

                    b.HasIndex("IncidentId")
                        .HasDatabaseName("ix_zones_incident_id");

                    b.ToTable("zones", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Data.EventRecord", b =>
                {
                    b.Property<long>("Sequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Sequence"));

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<DateTimeOffset>("SimTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sim_time");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("source");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("type");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("visibility");

                    b.Property<DateTimeOffset>("WallTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("wall_time");

                    b.HasKey("Sequence")
                        .HasName("pk_events");

                    b.HasIndex("SessionId", "Sequence")
                        .HasDatabaseName("ix_events_session_id_sequence");

                    b.HasIndex("SessionId", "SimTime")
                        .HasDatabaseName("ix_events_session_id_sim_time");

                    b.ToTable("events", (string)null);
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Unit", b =>
                {
                    b.HasBaseType("Emergency_Response_Simulator.Core.Model.Resource");

                    b.Property<Guid?>("AssignedIncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("assigned_incident_id");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("callsign");

                    b.PrimitiveCollection<List<string>>("Capabilities")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("capabilities");

                    b.Property<bool>("CommsConnected")
                        .HasColumnType("boolean")
                        .HasColumnName("comms_connected");

                    b.Property<int>("CrewSize")
                        .HasColumnType("integer")
                        .HasColumnName("crew_size");

                    b.Property<TimeSpan?>("Eta")
                        .HasColumnType("interval")
                        .HasColumnName("eta");

                    b.Property<double>("Heading")
                        .HasColumnType("double precision")
                        .HasColumnName("heading");

                    b.Property<string>("HomeStation")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("home_station");

                    b.Property<DateTimeOffset?>("LastAvlUpdate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_avl_update");

                    b.Property<double>("SpeedKph")
                        .HasColumnType("double precision")
                        .HasColumnName("speed_kph");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("type");

                    b.HasIndex("AssignedIncidentId")
                        .HasDatabaseName("ix_resources_assigned_incident_id");

                    b.HasIndex("Callsign")
                        .HasDatabaseName("ix_resources_callsign");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_resources_status");

                    b.HasDiscriminator().HasValue("unit");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Alert", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.User", "AcknowledgedBy")
                        .WithMany()
                        .HasForeignKey("AcknowledgedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_users_acknowledged_by_id");

                    b.HasOne("Emergency_Response_Simulator.Core.Model.Incident", "Incident")
                        .WithMany("Alerts")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_incidents_incident_id");

                    b.HasOne("Emergency_Response_Simulator.Core.Model.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alerts_units_unit_id");

                    b.Navigation("AcknowledgedBy");

                    b.Navigation("Incident");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.GisFeature", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.GisLayer", "Layer")
                        .WithMany("Features")
                        .HasForeignKey("LayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_gis_features_gis_layers_layer_id");

                    b.Navigation("Layer");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Incident", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.User", "IncidentCommander")
                        .WithMany()
                        .HasForeignKey("IncidentCommanderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incidents_users_incident_commander_id");

                    b.Navigation("IncidentCommander");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.IncidentActionPlan", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incident_action_plans_users_approved_by_id");

                    b.HasOne("Emergency_Response_Simulator.Core.Model.Incident", "Incident")
                        .WithMany()
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_incident_action_plans_incidents_incident_id");

                    b.HasOne("Emergency_Response_Simulator.Core.Model.OperationalPeriod", "OperationalPeriod")
                        .WithMany()
                        .HasForeignKey("OperationalPeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_incident_action_plans_operational_periods_operational_perio");

                    b.HasOne("Emergency_Response_Simulator.Core.Model.User", "PreparedBy")
                        .WithMany()
                        .HasForeignKey("PreparedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_incident_action_plans_users_prepared_by_id");

                    b.OwnsMany("Emergency_Response_Simulator.Core.Model.IapAssignment", "Assignments", b1 =>
                        {
                            b1.Property<Guid>("IncidentActionPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Assignment")
                                .IsRequired();

                            b1.Property<string>("Group");

                            b1.Property<Guid>("ResourceId");

                            b1.HasKey("IncidentActionPlanId", "__synthesizedOrdinal");

                            b1.ToTable("incident_action_plans");

                            b1
                                .ToJson("assignments")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IncidentActionPlanId")
                                .HasConstraintName("fk_incident_action_plans_incident_action_plans_incident_action_p");
                        });

                    b.OwnsMany("Emergency_Response_Simulator.Core.Model.IapObjective", "Objectives", b1 =>
                        {
                            b1.Property<Guid>("IncidentActionPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("Order");

                            b1.Property<string>("PerformanceTarget");

                            b1.Property<string>("ResourcesSummary");

                            b1.Property<string>("Statement")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Tactics")
                                .IsRequired();

                            b1.HasKey("IncidentActionPlanId", "__synthesizedOrdinal");

                            b1.ToTable("incident_action_plans");

                            b1
                                .ToJson("objectives")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IncidentActionPlanId")
                                .HasConstraintName("fk_incident_action_plans_incident_action_plans_incident_action_p");
                        });

                    b.OwnsMany("Emergency_Response_Simulator.Core.Model.IapPosition", "Organization", b1 =>
                        {
                            b1.Property<Guid>("IncidentActionPlanId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired();

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(40);

                            b1.Property<Guid?>("UserId");

                            b1.HasKey("IncidentActionPlanId", "__synthesizedOrdinal");

                            b1.ToTable("incident_action_plans");

                            b1
                                .ToJson("organization")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("IncidentActionPlanId")
                                .HasConstraintName("fk_incident_action_plans_incident_action_plans_incident_action_p");
                        });

                    b.Navigation("ApprovedBy");

                    b.Navigation("Assignments");

                    b.Navigation("Incident");

                    b.Navigation("Objectives");

                    b.Navigation("OperationalPeriod");

                    b.Navigation("Organization");

                    b.Navigation("PreparedBy");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.OperationalPeriod", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.Incident", "Incident")
                        .WithMany("OperationalPeriods")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operational_periods_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Report", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.Incident", "Incident")
                        .WithMany("Reports")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_reports_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Resource", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.Agency", "Agency")
                        .WithMany("Resources")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_resources_agencies_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.User", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.Agency", "Agency")
                        .WithMany("Users")
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_users_agencies_agency_id");

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Zone", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.Incident", "Incident")
                        .WithMany("Zones")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_zones_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Unit", b =>
                {
                    b.HasOne("Emergency_Response_Simulator.Core.Model.Incident", "AssignedIncident")
                        .WithMany("AssignedUnits")
                        .HasForeignKey("AssignedIncidentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_resources_incidents_assigned_incident_id");

                    b.Navigation("AssignedIncident");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Agency", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.GisLayer", b =>
                {
                    b.Navigation("Features");
                });

            modelBuilder.Entity("Emergency_Response_Simulator.Core.Model.Incident", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("AssignedUnits");

                    b.Navigation("OperationalPeriods");

                    b.Navigation("Reports");

                    b.Navigation("Zones");
                });
#pragma warning restore 612, 618
        }
    }
}
